# meta-agentos/conf/layer.conf

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/images/*.bb"

BBFILE_COLLECTIONS += "meta-agentos"
BBFILE_PATTERN_meta-agentos := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-agentos = "10"

#LAYERDEPENDS_meta-agentos = "core meta-oe meta-python meta-networking meta-raspberrypi"
LAYERDEPENDS_meta-agentos = "core openembedded-layer networking-layer meta-python raspberrypi"

LAYERSERIES_COMPAT_meta-agentos = "whinlatter walnascar scarthgap styhead"
