# agentos.conf

require conf/distro/poky.conf

DISTRO = "agentos"
DISTRO_NAME = "AgentOS"
DISTRO_VERSION = "1"

DISTRO_FEATURES = "acl ipv4 ipv6 usbgadget usbhost xattr pci nfc vfat seccomp multiarch ldconfig"
DISTRO_FEATURES += " systemd"
DISTRO_FEATURES += " rauc"

# support building Xen, KVM, Libvirt, and associated
# packages necessary for constructing OE-based virtualized solutions.
DISTRO_FEATURES += "virtualization"

#DISTRO_EXTRA_RDEPENDS=""
#DISTRO_EXTRA_RRECOMMENDS=""

#TCLIBC=""

INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"

#SPLASH = "plymouth"
#PREFERRED_PROVIDER_virtual/psplash = "plymouth"

#SPLASH = "psplash"
#PREFERRED_PROVIDER_virtual/psplash = "psplash"

# Vanilla psplash is able to use vc4 DRM fb
#SPLASH = "psplash-drm"
#PREFERRED_PROVIDER_virtual/psplash = "psplash-drm"
